### ISSUE TITLE
Not time series at all!

### ISSUE THREAD

**Issue by lcltech** [Etv500/EMD-SVR-and-VMD-SVR-stock-index-prediction#1]
I have read the paper and looked at the code. This have nothing to do with time series prediction!
The SVR is trained with the decomposed modes to output the actual signal. Essentially training it to sum up the IMF's:

reg_cv.fit(u_train.T, y_train[1:])

So if you then feed it the decomposed test signal:

y_pred = reg_cv.predict(u_test.T)

of course your "prediction" will be close to test signal. You are pretty much just asking to sum up the IMF's.

How would you be able to decompose signals from the future?

**Comment by Emiem2017** [comment]
两张png图也画错了

**Comment by Etv500** [comment]
You can then forecast the modes and compose the actual signal ie the price hence the time series.
